# -*- coding: utf-8 -*-
"""Ai for gov and policy project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8lZN4Oq6yY8UMsH8m4VJjmJZx-HGRAx

# Data Transformer
"""

import pandas as pd
import numpy as np

class dt:
  # conditional_row_filter, multi_conditional_row_filter, sort_values, pivot_table, filter_df_by_id were removed as unused.
  def random_n(self, df, n=None, frac=None, on_switch=False, random_state=None, replace=False):
    self.df = df
    self.n = n
    self.frac = frac
    self.on_switch = on_switch
    self.random_state = random_state
    self.replace = replace

    if self.on_switch == True:
      df_temp = self.df.sample(n=self.n, frac=self.frac, replace=self.replace, random_state=self.random_state)
      return df_temp
    else: return self.df

print(dir(dt))

"""# Helper functions"""

import ctypes

class hf:
  # clean_din_list, remove_nonstring_items, remove_leading_zeros, add_leading_zeros,
  # remove_duplicates, df_remove_uknown_sex, decimal_place, p_value_recat,
  # add_number_to_list, and done_alert were removed as unused.

  # Only df_remove_duplicates is retained as it is used in DataPreparationNameEthnicityProject.
  @staticmethod
  def df_remove_duplicates(df, col_list) -> object:
      '''Remove duplicated records (retaining first) when they have the same values on all the variables on `col_list`'''
      return df.drop_duplicates(subset=col_list, keep='first')

print(dir(hf))

"""# Data Pre-processing"""

import ctypes
import sys
from abc import ABC, abstractmethod
import pandas as pd
import numpy as np
import os

class DataPreparation(ABC):
	def __init__(self):
		self.control_panel = {
			'save_file_switch': True, # WARNING: Will overwrite existing files if True
			'df_subsampling_switch': True,  # WARNING: Switch to False in production. Set to True for replication as per study design.
			'df_subsampling_n': 50000, # Subsampling to manage computational load, as often done in larger studies.
			'random_seed': 888, # Fixed random seed for reproducibility of study results.
			'df_remove_dup_switch': True, # Data cleaning step as per study methodology.
			'df_remove_missing_switch': True, # Data cleaning step as per study methodology.
			'result_printout_switch': True,
			'done_switch': False,
			}

	@abstractmethod
	def dir_name(self):
		pass

	@abstractmethod
	def file_name(self):
		pass

	@abstractmethod
	def import_ref_data(self):
		pass

	@abstractmethod
	def import_main_data(self):
		pass

	@abstractmethod
	def resample_row(self):
		pass

	# These can remain concrete methods with 'pass' if they are optional to implement
	def rename_var(self):
		pass

	def remove_var(self):
		pass

	def create_var(self):
		pass

	def merge_datasets(self):
		pass

	def remove_row_duplicate(self):
		pass

	def remove_row_missing(self):
		pass

	def sort_row(self):
		pass

	def show_processed_data(self):
		pass

	def file_name(self):
		self.file_census1901 = 'Mock_Data.csv'
		self.file_ethnicityRecatMap = 'Ethnicity_Recategorication_Map.csv'

	def import_ref_data(self):
		self.df_ethnicRecat = pd.read_csv(self.ref_data_dir+self.file_ethnicityRecatMap)

	def import_main_data(self):
		self.df_census1901: pd.read.csv(self.raw_data_dir+self.file_census1901)

	def resample_row(self):
		pass

	def data_preparation_steps(self):
		self._pandas_output_setting()
		self.dir_name()
		self.file_name()
		self.import_ref_data()
		self.import_main_data()
		self.resample_row()
		self.rename_var()
		self.remove_var()
		self.create_var()
		self.merge_datasets()
		self.remove_row_duplicate()
		self.remove_row_missing()
		self.sort_row()
		self.show_processed_data()

	def _pandas_output_setting(self):
		'''Set pandas output display setting'''
		pd.set_option('display.max_rows', 500)
		pd.set_option('display.max_columns', 500)

	# Class helper functions
	def df_info(self, *dfs, full_info=False):
	  '''Print related df info'''
	  full_info = self.control_panel['result_printout_switch']
	  for df in dfs:
	    print('length:', len(df))
	    if full_info:
	      print(df.info())
	      print(df.head())


	def random_sampling(self, *dfs, set_replace=False) -> tuple:
	  '''Setting default value of 'sampling with replacement'''
	  for df in dfs:
	    if (self.control_panel['df_subsampling_n'] > len(df)):
	      print ("""\nWarning: Specified subsample size is larger than the total no. of row of some of the dataset. As a result, resampling with replacement will be done to reach specified subsample size.""")
	      set_replace = True
	  df_list = []
	  for df in dfs:
	      dt_obj = dt()
	      df = dt_obj.random_n(df, n=self.control_panel['df_subsampling_n'], on_switch=self.control_panel['df_subsampling_switch'],
	                          random_state=self.control_panel['random_seed'], replace=set_replace)
	      df_list.append(df)
	  if len(df_list) >= 2:
	      return tuple(df_list) # convert list to tuple type
	  else:
	      return df_list[0]

class DataPreparationNameEthnicityProject(DataPreparation):
  def dir_name(self):
    self.main_dir = os.getcwd() # Setting Main current directory
    # In Colab, the data files are directly in /content/
    self.raw_data_dir = self.main_dir + os.sep # Use os.sep for platform-agnostic path separator
    self.ref_data_dir = self.main_dir + os.sep # Use os.sep for platform-agnostic path separator

    # Define paths for processed and result data directories, and ensure they exist
    self.processed_data_dir = os.path.join(self.main_dir, 'data', 'processed') + os.sep
    self.result_dir = os.path.join(self.main_dir, 'result') + os.sep

    os.makedirs(self.processed_data_dir, exist_ok=True)
    os.makedirs(self.result_dir, exist_ok=True)


  def import_ref_data(self):
    # Importing reference data, similar to the study's data loading phase (e.g., supplementary data).
    self.df_ethnicRecat = pd.read_csv(self.ref_data_dir+self.file_ethnicityRecatMap, encoding='utf-8', low_memory=False)

  def import_main_data(self):
    # Importing the main dataset, mimicking the primary data source of the study.
    self.df_census1901 = pd.read_csv(self.raw_data_dir+self.file_census1901, encoding='utf-8', low_memory=False)
    self.df_census1901_len_original = len(self.df_census1901)

  def resample_row(self):
    # Subsampling of rows, as often done in studies for manageability or specific analysis (e.g., Table 2 in the paper).
    if self.control_panel['df_subsampling_switch']:
      self.df_census1901 = self.random_sampling(self.df_census1901)
      self.df_census1901_len_resampled = len(self.df_census1901)

  def merge_datasets(self):
    # Merging with ethnicity recategorization map as per the study's data linking step.
    self.df_census1901 = self.df_census1901.merge(self.df_ethnicRecat, on='ETHNICITY', how='left')

  def remove_row_duplicate(self):
    # Removal of duplicate records based on key identifiers, crucial for data integrity in the study.
    if self.control_panel['df_remove_dup_switch']:
      self.df_census1901 = hf.df_remove_duplicates(self.df_census1901, ['NAME', 'ETHNICITY', 'SEX', 'LOC'])
      self.df_census1901_len_dup_removed = len(self.df_census1901)

  def remove_row_missing(self):
    # Handling missing values by dropping rows with critical missing information, as per the study's data cleaning.
    if self.control_panel['df_remove_missing_switch']:
      self.df_census1901 = self.df_census1901.dropna(subset=['NAME', 'ETHNICITY', 'LOC'])
      self.df_census1901_len_missing_removed = len(self.df_census1901)

  def show_processed_data(self):
    # Displaying data flow and descriptive statistics, similar to tables/figures in the study document.
    if self.control_panel['result_printout_switch']:

      describe_cat_var('SEX', self.df_census1901, 'SEX')
      describe_cat_var('ETHNICITY', self.df_census1901, 'ETHNICITY')
      print('/// Subject N Flow: ///')
      print('Census 1901 (N), original: {}'.format(self.df_census1901_len_original))
      if self.control_panel['df_subsampling_switch']:
        print('Census 1901 (N), after resampling: {}'.format(self.df_census1901_len_resampled))
        if self.control_panel['df_remove_dup_switch']:
          print('Census 1901 (N), after duplicates removed: {}'.format(self.df_census1901_len_dup_removed))
          if self.control_panel['df_remove_missing_switch']:
            print('Census 1901 (N), after records with missing values removed: {}'.format(self.df_census1901_len_missing_removed))



# Helper functions
from typing import Self

def result_decor(func):
	def print_result(df_key, df, var_name):
		print('/////////////////////////////////////////')
		print('/////////////////////////////////////////')
		func(df_key, df, var_name)
		print('/////////////////////////////////////////')
		print('/////////////////////////////////////////'+'\n')
	return print_result

@result_decor
def describe_num_var(df_key, df, var_name):
	df_head_n = 5
	print('Dataset name: {}'.format(df_key))
	print('{}, min: {}'.format(var_name, df[var_name].min()))
	print('{}, max: {}'.format(var_name, df[var_name].max()))
	print('{}, 25%tile, 50%tile, 75%tile:\n{}'.format(var_name, str(df[var_name].quantile([.25, .5, .75]))))
	print('{}, top value counts:\n{}'.format(var_name, str(df[var_name].value_counts().head(df_head_n))))

@result_decor
def describe_cat_var(df_key, df, var_name):
	df_head_n = 5
	print('Dataset name: {}'.format(df_key))
	print('{}, top value counts:\n{}'.format(var_name, str(df[var_name].value_counts().head(df_head_n))))


# Main function

def main(on_switch=False):
	if on_switch:
		obj = DataPreparationNameEthnicityProject()
		obj.data_preparation_steps()

		if obj.control_panel['done_switch']:
			hf.done_alert()

if __name__ == '__main__':
	main(on_switch=False)

dp = DataPreparationNameEthnicityProject()
dp.data_preparation_steps()
df = dp.df_census1901
df.head()

"""#Feature Generation"""

import re
import string
import random
!pip install Metaphone
from metaphone import doublemetaphone

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer, f1_score, recall_score, precision_score

Local_control_panel = {'save_df_switch': True,
                       'feature_gen_switch': True,
                       'df_subsampling_switch': False,
                       'df_subsampling_n':1*1000,
                       'random_seed': 888,
                       'done_switch': False,
                       }

class FeatureCreation(ABC):
  def feature_generation_steps(self, df):
    self.df=df
    self.data_prep()
    self.create_features(on_switch=Local_control_panel['feature_gen_switch'])

    if Local_control_panel['save_df_switch']:
      print("Final Dataset Ready")
    return self.df

  def data_prep(self):
    pass
  def create_features(self, on_switch=True):
    pass

# Feature generation control panel (simplified slightly from original)
Local_control_panel = {'feature_gen_switch': True}

class FeatureCreation(DataPreparationNameEthnicityProject):
  def feature_generation_steps(self, df):
    self.df = df

    if Local_control_panel['feature_gen_switch']:
      self.create_features()

    return self.df

  def create_features(self):
    # Standardizing all string columns to lowercase and converting 'nan' strings to np.nan
    # This replaces the problematic `format_all_var` method and ensures proper type handling.
    for col in self.df.select_dtypes(include='object').columns:
        self.df[col] = self.df[col].astype(str).str.lower()
        self.df[col] = self.df[col].replace('nan', np.nan)


    # Feature creation steps closely follow the methodology described in the study.
    # These methods transform raw data into features used for prediction.
    self.format_name_var()
    self.format_loc_var()
    self.format_ethnic_var()

    self.create_name_feature()
    self.create_loc_feature()
    self.create_dummy_feature()
#removed the file importing, saving and abstract classes for simplicity of execution based on the part I am replicating



  # The original format_all_var method is removed as its functionality is now handled at the start of create_features.
  # def format_all_var(self):
  #       self.df = self.df.apply(lambda x: x.astype(str).str.lower()) # Standardizing text data to lowercase as per study preprocessing.

  def format_ethnic_var(self):
        # These steps for ethnic variable formatting are based on the study's specific categorization logic.
        # Note: The original 'ETHNICITY_RECAT' is likely the 'ETHNICITY_RECAT_x' from the merge if not renamed
        # However, the subsequent filtering uses ETHNICITY_RECAT, so ensure it refers to the correct base column

        self.df['ETHNICITY_RECAT'] = self.df['ETHNICITY_RECAT_x']

        self.df['ETHNICITY_RECAT_V2'] = self.df.apply(map_two_columns, var_base='ETHNICITY_RECAT',
            var_overwrite='AB_GROUP', axis=1)
        self.df['ETHNICITY_RECAT_V3'] = self.df.apply(map_two_columns, var_base='ETHNICITY_RECAT',
            var_overwrite='AB_TRIBE', axis=1)
        self.df['ETHNICITY_RECAT_V4'] = self.df.apply(map_two_columns, var_base='ETHNICITY_RECAT',
            var_overwrite='AB_LANG', axis=1)

        self.df['ETHNICITY_RECAT'] = self.df.apply(remove_sp_output, var='ETHNICITY_RECAT', axis=1)
        self.df['ETHNICITY_RECAT_V2'] = self.df.apply(remove_sp_output, var='ETHNICITY_RECAT_V2', axis=1)
        self.df['ETHNICITY_RECAT_V3'] = self.df.apply(remove_sp_output, var='ETHNICITY_RECAT_V3', axis=1)
        self.df['ETHNICITY_RECAT_V4'] = self.df.apply(remove_sp_output, var='ETHNICITY_RECAT_V4', axis=1)

        # Remove rows with missing values
        self.df = self.df[self.df['ETHNICITY_RECAT'].notnull()]
        self.df = self.df[self.df['ETHNICITY_RECAT_V2'].notnull()]

  def format_sex_var(self):
        # Standardizing sex variable as specified in the study's data preparation.
        self.df['SEX'] = self.df.apply(format_sex_var, axis=1)

  def format_name_var(self):
        # Comprehensive name cleaning and standardization, essential for feature extraction as detailed in the study.
        self.df['NAME_V2'] = self.df.apply(remove_single_char, var='NAME', axis=1)
        self.df['NAME_V2'] = self.df.apply(remove_symbol, var='NAME_V2', axis=1)
        self.df['NAME_V2'] = self.df.apply(remove_number, var='NAME_V2', axis=1)
        self.df['NAME_V2'] = self.df.apply(remove_title, var='NAME_V2', axis=1)
        self.df['NAME_V2'] = self.df.apply(remove_double_space, var='NAME_V2', axis=1)
        self.df['NAME_V2'] = self.df.apply(remove_leading_space, var='NAME_V2', axis=1)
        self.df['NAME_V2'] = self.df.apply(remove_trailing_space, var='NAME_V2', axis=1)
        self.df = self.df[self.df['NAME_V2']!='']

  def format_loc_var(self):
        # Location variable cleaning, specific to handling multilingual entries often found in historical data.

        self.df['LOC'] = self.df.apply(lambda row: re.sub(r'\s*\(.+?\)|\s*/\w+', '', row['LOC']), axis=1)

  def create_name_feature(self):
        # Creation of various name-based features (structural, phonetic, substring) as critical components of the study's model.
        self.df['NAME_FIRST'] = self.df.apply(get_first_name, var='NAME_V2', axis=1)
        self.df['NAME_MIDDLE'] = self.df.apply(get_middle_name, var='NAME_V2', axis=1)
        self.df['NAME_LAST'] = self.df.apply(get_last_name, var='NAME_V2', axis=1)

        self.df['NAME_ENTITY_COUNT'] = self.df.apply(name_entity_count, var='NAME', axis=1)
        self.df['NAME_TOTAL_LENGTH'] = self.df.apply(get_word_length, var='NAME_V2', axis=1)
        self.df['NAME_AVG_LENGTH'] = self.df.apply(get_avg_word_length, var='NAME_V2', axis=1)
        self.df['NAME_VOWEL_COUNT'] = self.df.apply(vowel_count, var='NAME_V2', axis=1)
        self.df['NAME_VOWEL_RATIO'] = self.df.apply(get_vowel_ratio, var='NAME_V2', axis=1)

        self.df['NAME_FIRST_FIRSTCHAR'] = self.df.apply(get_edge_char, var='NAME_FIRST', edge='first', axis=1)
        self.df['NAME_FIRST_LASTCHAR'] = self.df.apply(get_edge_char, var='NAME_FIRST', edge='last', axis=1)
        self.df['NAME_MIDDLE_FIRSTCHAR'] = self.df.apply(get_edge_char, var='NAME_MIDDLE', edge='first', axis=1)
        self.df['NAME_MIDDLE_LASTCHAR'] = self.df.apply(get_edge_char, var='NAME_MIDDLE', edge='last', axis=1)
        self.df['NAME_LAST_FIRSTCHAR'] = self.df.apply(get_edge_char, var='NAME_LAST', edge='first', axis=1)
        self.df['NAME_LAST_LASTCHAR'] = self.df.apply(get_edge_char, var='NAME_LAST', edge='last', axis=1)

        self.df['NAME_FIRST_1LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_FIRST', substring_len=1, axis=1)
        self.df['NAME_FIRST_2LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_FIRST', substring_len=2, axis=1)
        self.df['NAME_FIRST_3LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_FIRST', substring_len=3, axis=1)
        self.df['NAME_FIRST_4LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_FIRST', substring_len=4, axis=1)
        self.df['NAME_FIRST_5LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_FIRST', substring_len=5, axis=1)
        self.df['NAME_FIRST_6LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_FIRST', substring_len=6, axis=1)
        self.df['NAME_MIDDLE_1LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_MIDDLE', substring_len=1, axis=1)
        self.df['NAME_MIDDLE_2LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_MIDDLE', substring_len=2, axis=1)
        self.df['NAME_MIDDLE_3LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_MIDDLE', substring_len=3, axis=1)
        self.df['NAME_MIDDLE_4LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_MIDDLE', substring_len=4, axis=1)
        self.df['NAME_MIDDLE_5LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_MIDDLE', substring_len=5, axis=1)
        self.df['NAME_MIDDLE_6LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_MIDDLE', substring_len=6, axis=1)
        self.df['NAME_LAST_1LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_LAST', substring_len=1, axis=1)
        self.df['NAME_LAST_2LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_LAST', substring_len=2, axis=1)
        self.df['NAME_LAST_3LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_LAST', substring_len=3, axis=1)
        self.df['NAME_LAST_4LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_LAST', substring_len=4, axis=1)
        self.df['NAME_LAST_5LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_LAST', substring_len=5, axis=1)
        self.df['NAME_LAST_6LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_LAST', substring_len=6, axis=1)

        self.df['NAME_FULL_1LETTER_SUBSTRINGS'] = self.df.apply(get_substring, var='NAME_V2', substring_len=1, axis=1)
        self.df['NAME_FULL_METAPHONE'] = self.df.apply(get_double_metaphone, var='NAME_V2', axis=1)

  def create_loc_feature(self):
        # Creation of location-based features, important for geographical context in the study.
        self.df['LOC_COUNTRY'] = self.df.apply(get_country, var='LOC', axis=1)
        self.df['LOC_PROVINCE'] = self.df.apply(get_province, var='LOC', axis=1)
        self.df['LOC_DISTRICT'] = self.df.apply(get_district, var='LOC', axis=1)
        self.df['LOC_DISTRICT_SUB'] = self.df.apply(get_subdistrict, var='LOC', axis=1)
        self.df['LOC_DISTRICT_FULL'] = self.df.apply(get_full_district_description, var='LOC', axis=1)
        self.df['LOC_ENTITY_COUNT'] = self.df.apply(loc_entity_count, var='LOC', axis=1)
        self.df['LOC_ENTITY_LIST'] = self.df.apply(loc_entity_simplified_list, var='LOC', axis=1)

  def create_dummy_feature(self):
        # Dummy features are included to establish a baseline performance in the study's evaluations (e.g., Table 2).
        self.df['DUMMY_STRING'] = self.df.apply(get_random_str, axis=1)
        self.df['DUMMY_INTEGER'] = self.df.apply(get_random_int, axis=1)

# Local helper functions
######################################################################
# Ethnicity var
def map_two_columns(df, var_base, var_overwrite):
    if (df[var_overwrite] != np.nan) & (df[var_overwrite] != '') & (df[var_overwrite] != 'nan'):
        return df[var_overwrite]
    else:
        return df[var_base]

def remove_sp_output(df, var, sp_val='out'):
    if df[var] == sp_val:
        return np.nan
    else:
        return df[var]

# Sex var
def format_sex_var(df):
    if df['SEX'] == 'male':
        return 'm'
    elif df['SEX'] == 'female':
        return 'f'

# Name var
def remove_single_char(df, var):
    return re.sub(r'\\b\\w\\b', '', df[var])

def remove_symbol(df, var):
    return re.sub(r'[?:;()/*%^&#@$!`.].', '', df[var])

def remove_number(df, var):
    return re.sub(r'\\d+','', df[var])

def remove_title(df, var):
    return ' '.join([i for i in df[var].split() if ((i!='mr') and (i!='mrs') and (i!='md')
        and (i!='ms') and (i!='sir') and (i!='madam') and (i!='dr') and (i!='msc') and (i!='frs') and (i!='phd')
        and (i!='rev') and (i!='pr') and (i!='prof') and (i!='adv') and (i!='mz') and (i!="ma'am") and (i!='st')
        and (i!='esq') and (i!='hon') and (i!='jr') and (i!='messrs') and (i!='mmes') and (i!='msgr') and (i!='rt hon'))])

def remove_double_space(df, var):
    return re.sub(r'  ', ' ', df[var])

def remove_leading_space(df, var):
    return re.sub(r'^[ \\t]+', '', df[var])

def remove_trailing_space(df, var):
    return re.sub(r'[ \\t]+$', '', df[var])

def get_first_name(df, var):
    name_entity = df[var].split()
    if (len(name_entity) == 0)|(len(name_entity) == 1):
        return ''
    else:
        return name_entity[0]

def get_middle_name(df, var):
    name_entity = df[var].split()
    if len(name_entity) >= 3:
        return ' '.join(name_entity[1:len(name_entity)-1])
    else:
        return ''

def get_last_name(df, var):
    name_entity = df[var].split()
    if len(name_entity) == 0:
        return ''
    else:
        return name_entity[-1]

def name_entity_count(df, var):
    name_entity = [x.strip() for x in df[var].split(' ')]
    return len(name_entity)

def get_word_length(df, var):
    space = 0
    for i in df[var]:
        if i == ' ':
            space += 1
    return len(df[var]) - space

def get_avg_word_length(df, var):
    space = 0
    for i in df[var]:
        if i == ' ':
            space += 1
    length = len(df[var]) - space
    name_entity = float(space + 1)
    avg = ('%.2f' % round(float(length/name_entity), 2))
    return avg

def vowel_count(df, var):
    return len(re.findall('[aeiou]', df[var]))

def get_vowel_ratio(df, var):
    vowel_count = len(re.findall('[aeiou]', df[var]))
    space = 0
    for i in df[var]:
        if i == ' ':
            space += 1
    total_length = len(df[var]) - space
    return ('%.2f' % round(vowel_count/total_length, 2))

def get_edge_char(df, var, edge=None):
    assert (edge=='first')|(edge=='last'), 'Error: Param `edge` is neither `first` nor `last`.'
    if edge == 'first':
        try:
            return df[var][0]
        except:
            return ''
    elif edge == 'last':
        try:
            return df[var][-1]
        except:
            return ''

def get_substring(df, var, substring_len) -> str:
    placeholder = []
    try:
        for i in range(0, len(df[var])):
            substring = df[var][i:i+substring_len]
            substring_cleaned = re.sub(' ', '', substring)
            substring_cleaned = substring_cleaned.strip()

            if len(substring_cleaned) == substring_len:
                placeholder.append(substring_cleaned)

        liststring = ', '.join(map(str, placeholder))
        return liststring
    except:
        return ''

def get_double_metaphone(df, var):
    placeholder = []
    name_entity = [x.strip() for x in df[var].split(' ')]
    try:
        for i in name_entity:
            placeholder.append(doublemetaphone(i)[0])

            if len(doublemetaphone(i)[1]) > 0:
                placeholder.append(doublemetaphone(i)[1])

        liststring = ', '.join(map(str, placeholder))
        return liststring

    except:
        return ''

# Location var
def remove_french_words(df, var):

    # Using lambda for apply to correctly pass the series value.
    return re.sub(r'\s*\(.+?\)|\s*/\w+', '', df[var])

def get_country(df, var):
    loc_entity = [x.strip() for x in df[var].split(',')]
    return loc_entity[-1]

def get_province(df, var):
    loc_entity = [x.strip() for x in df[var].split(',')]
    return loc_entity[-2]

def get_district(df, var):
    loc_entity = [x.strip() for x in df[var].split(',')]
    return loc_entity[-3]

def get_subdistrict(df, var):
    loc_entity = [x.strip() for x in df[var].split(',')]
    return loc_entity[-4]

def get_full_district_description(df, var):
    loc_entity = [x.strip() for x in df[var].split(',') if x != '']
    return ', '.join(loc_entity[0:-1])

def loc_entity_count(df, var):
    loc_entity = [x.strip() for x in df[var].split(',')]
    return len(loc_entity)

def loc_entity_simplified_list(df, var):
    loc_entity = [x.strip() for x in df[var].split(',')]
    loc_entity_simplified = [re.sub(r' \\(.*\\)', '', x) for x in loc_entity if x != '']
    loc_list = loc_entity_simplified[0:-1]
    liststring = ', '.join(map(str, loc_list))
    return liststring

# Generic
def get_random_str(df):
    rands_chars = np.array(list(string.ascii_letters + string.digits), dtype=(np.str_, 1))
    n_chars = np.random.randint(5, 15)
    return ''.join(np.random.choice(rands_chars, n_chars))

def get_random_int(df):
    return np.random.randint(1, 50)

dp = DataPreparationNameEthnicityProject()
dp.data_preparation_steps()
df = dp.df_census1901

fc = FeatureCreation()
df_features = fc.feature_generation_steps(df)

# Convert string-numeric columns to numeric type
df_features['NAME_AVG_LENGTH'] = pd.to_numeric(df_features['NAME_AVG_LENGTH'], errors='coerce')
df_features['NAME_VOWEL_RATIO'] = pd.to_numeric(df_features['NAME_VOWEL_RATIO'], errors='coerce')

df_features.head()

# Grouping based on the study's feature sets, as outlined in Table 2 of the study.
feature_groups = {
    'dummy': ['DUMMY_STRING', 'DUMMY_INTEGER'], # Baseline features to compare against.
    'sex_only': ['SEX'], # Gender-based features.
    'name_basic': ['NAME_FIRST', 'NAME_MIDDLE', 'NAME_LAST', 'NAME_FIRST_FIRSTCHAR', 'NAME_FIRST_LASTCHAR', 'NAME_LAST_FIRSTCHAR', 'NAME_LAST_LASTCHAR'], # Basic structural name features.
    'name_substrings': [col for col in df_features.columns if 'SUBSTRINGS' in col], # Features capturing letter patterns within names.
    'name_numeric': ['NAME_ENTITY_COUNT', 'NAME_TOTAL_LENGTH', 'NAME_AVG_LENGTH', 'NAME_VOWEL_COUNT', 'NAME_VOWEL_RATIO'], # Quantitative name characteristics.
    'name_phonetic': ['NAME_FULL_METAPHONE'], # Features based on the phonetic representation of names.
    'loc_all': ['LOC_COUNTRY', 'LOC_PROVINCE', 'LOC_DISTRICT', 'LOC_DISTRICT_SUB', 'LOC_ENTITY_LIST'], # All location-based features.
}

# Define the major combined sets for the rows in Table 2 of the study.
table_2_rows = {
    "Dummy": feature_groups['dummy'],
    "Sex only": feature_groups['sex_only'],
    "Basic name features": feature_groups['name_basic'],
    "Name substring features": feature_groups['name_substrings'],
    "Name numeric features": feature_groups['name_numeric'],
    "Phonetic name features": feature_groups['name_phonetic'],
    "All name": feature_groups['name_basic'] + feature_groups['name_substrings'] + feature_groups['name_numeric'] + feature_groups['name_phonetic'],
    "All location": feature_groups['loc_all'],
    "All name & location": feature_groups['name_basic'] + feature_groups['name_substrings'] + feature_groups['name_numeric'] + feature_groups['name_phonetic'] + feature_groups['loc_all']
}

import pandas as pd

non_numeric_cols = []
for col in df_features.columns:
    if not pd.api.types.is_numeric_dtype(df_features[col]):
        non_numeric_cols.append(col)

print("Non-numeric columns in df_features:")
for col in non_numeric_cols:
    print(col)

df_features.columns

"""# FEATURE SELECTION"""

def evaluate_feature_set(df, features, target='ETHNICITY_RECAT_x'):
    numeric_features = []
    text_features = []
    onehot_features = []

    # Define candidates for text features that will use CountVectorizer
    # These are typically string columns that represent lists of words/substrings or specific name parts
    # This approach is consistent with how the study handled textual features from names and locations but in line with my simplified pipeline
    count_vectorizer_candidates = [
        'NAME_FIRST', 'NAME_MIDDLE', 'NAME_LAST',
        'NAME_FIRST_FIRSTCHAR', 'NAME_FIRST_LASTCHAR',
        'NAME_LAST_FIRSTCHAR', 'NAME_LAST_LASTCHAR',
        'NAME_FULL_METAPHONE',
        'LOC_ENTITY_LIST' # This might be a liststring, needs specific handling
    ] + [col for col in features if 'SUBSTRINGS' in col] # Add all *_SUBSTRINGS columns if they are in 'features'

    for f in features:
        if pd.api.types.is_numeric_dtype(df[f]):
            numeric_features.append(f)
        elif f in count_vectorizer_candidates:
            text_features.append(f)
        else: # All other features not explicitly identified as numeric or text are treated as categorical for OneHotEncoder
            onehot_features.append(f)

    transformers_list = []

    if numeric_features:
        # StandardScaler for numerical features, a standard practice in machine learning studies.
        transformers_list.append(('num', StandardScaler(), numeric_features))

    if text_features:
        # CountVectorizer for text-based features, appropriate for analyzing patterns in names/location strings.
        # Limiting max_features to manage dimensionality, a common step in similar studies.
        for i, tf in enumerate(text_features):
            transformers_list.append((f'text_{tf}', CountVectorizer(token_pattern=r"(?u)\b\w+\b", max_features=500), tf))
            # Limiting max_features to avoid excessively sparse matrices and memory issues

    if onehot_features:
        # OneHotEncoder for other categorical features, avoiding assumptions about ordinality.
        transformers_list.append(('cat_onehot', OneHotEncoder(handle_unknown='ignore'), onehot_features))

    # If no transformers are defined, create a dummy one to avoid error
    if not transformers_list:
        raise ValueError("No features recognized for processing with current setup.")

    preprocessor = ColumnTransformer(
        transformers=transformers_list,
        remainder='drop' # Explicitly drop columns not handled by any transformer
    )

    # Logistic Regression as the classification model, often used as a strong baseline in research studies.
    from sklearn.linear_model import LogisticRegression
    clf = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000, random_state=888)) # Added random_state for reproducibility
    ])

    # 5-fold cross-validation as specified for Table 2 in the study, for robust performance evaluation.
    metrics = {
        'recall': make_scorer(recall_score, average='macro', zero_division=0, pos_label=None), # Sensitivity
        'precision': make_scorer(precision_score, average='macro', zero_division=0, pos_label=None), # Positive Predictive Value (PPV)
        'f1': make_scorer(f1_score, average='macro', zero_division=0, pos_label=None) # F1-score
    }
    scores = cross_validate(clf, df[features], df[target], cv=5, scoring=metrics)
    return scores

results_list = []
# Loop through table_2_rows dictionary
for group_name, column_list in table_2_rows.items():
  print(f"Processing: {group_name}")
  # Run cross-validation function
  scores = evaluate_feature_set(df_features, column_list)
  # Collect the mean scores (from the 5 folds)
  results_list.append({
  'Feature Set': group_name,
  'Sensitivity': scores['test_recall'].mean(),
  'PPV': scores['test_precision'].mean(),
  'F1-score': scores['test_f1'].mean()
  })
# Create the final Table 2 dataframe
table_2_final = pd.DataFrame(results_list)
display(table_2_final)